In [ ]:
import pandas as pd
import matplotlib.pyplot as plot
%matplotlib inline

In [3]:
df = pd.read_csv("run_or_walk.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88588 entries, 0 to 88587
Data columns (total 11 columns):
date              88588 non-null object
time              88588 non-null object
username          88588 non-null object
wrist             88588 non-null int64
activity          88588 non-null int64
acceleration_x    88588 non-null float64
acceleration_y    88588 non-null float64
acceleration_z    88588 non-null float64
gyro_x            88588 non-null float64
gyro_y            88588 non-null float64
gyro_z            88588 non-null float64
dtypes: float64(6), int64(2), object(3)
memory usage: 7.4+ MB


In [5]:
df.columns

Index(['date', 'time', 'username', 'wrist', 'activity', 'acceleration_x',
       'acceleration_y', 'acceleration_z', 'gyro_x', 'gyro_y', 'gyro_z'],
      dtype='object')

In [6]:
from sklearn.model_selection import train_test_split
X, y = df.iloc[:, 5:].values,df.iloc[:, 4].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [7]:
print(X_train.shape)
print(y_test[0:10])

(70870, 6)
[1 0 0 1 1 1 0 1 1 1]


In [8]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

In [9]:
classifier.fit(X_train,y_train)

GaussianNB(priors=None)

In [10]:
y_predict = classifier.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score

In [12]:
accuracy = accuracy_score(y_predict,y_test)

In [13]:
print(accuracy)

0.955469014561


In [14]:
from sklearn.metrics import confusion_matrix

In [15]:
conf_mat =confusion_matrix(y_predict,y_test)

In [16]:
print(conf_mat)

[[8583  699]
 [  90 8346]]


In [17]:
from sklearn.metrics import classification_report
target_names = ["Walk","Run"]

In [18]:
print(classification_report(y_test, y_predict, target_names=target_names))

             precision    recall  f1-score   support

       Walk       0.92      0.99      0.96      8673
        Run       0.99      0.92      0.95      9045

avg / total       0.96      0.96      0.96     17718



In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88588 entries, 0 to 88587
Data columns (total 11 columns):
date              88588 non-null object
time              88588 non-null object
username          88588 non-null object
wrist             88588 non-null int64
activity          88588 non-null int64
acceleration_x    88588 non-null float64
acceleration_y    88588 non-null float64
acceleration_z    88588 non-null float64
gyro_x            88588 non-null float64
gyro_y            88588 non-null float64
gyro_z            88588 non-null float64
dtypes: float64(6), int64(2), object(3)
memory usage: 7.4+ MB


In [23]:
from sklearn.model_selection import train_test_split
X, y = df.iloc[:, [5,6,7]].values,df.iloc[:, 4].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [24]:
classifier.fit(X_train,y_train)
y_predict = classifier.predict(X_test)
accuracy_score(y_predict,y_test)

0.95659781013658429

In [25]:
print(conf_mat)

[[8583  699]
 [  90 8346]]


In [ ]:
# 2 Method solution 

In [1]:
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
# 1. Load the kinematics dataset as measured on mobile sensors from the file “run_or_walk.csv”.
# List out the columns in the dataset.

In [2]:
data = pd.read_csv("run_or_walk.csv")
data.head()

date                time username  wrist  activity  acceleration_x  \
0  2017-6-30  13:51:15:847724020   viktor      0         0          0.2650   
1  2017-6-30  13:51:16:246945023   viktor      0         0          0.6722   
2  2017-6-30  13:51:16:446233987   viktor      0         0          0.4399   
3  2017-6-30  13:51:16:646117985   viktor      0         0          0.3031   
4  2017-6-30  13:51:16:846738994   viktor      0         0          0.4814   

   acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z  
0         -0.7814         -0.0076 -0.0590  0.0325 -2.9296  
1         -1.1233         -0.2344 -0.1757  0.0208  0.1269  
2         -1.4817          0.0722 -0.9105  0.1063 -2.4367  
3         -0.8125          0.0888  0.1199 -0.4099 -2.9336  
4         -0.9312          0.0359  0.0527  0.4379  2.4922

In [ ]:
# 2. Let the target variable ‘y’ be the activity and assign all the columns after it to ‘x’.

In [3]:
X = data.iloc[:, 5:]
Y = data["activity"]

In [4]:
# 3. Using Scikit-learn fit a Gaussian Naive Bayes model and observe the accuracy.
# Generate a classification report using scikitlearn.

In [5]:
train_x, test_x, train_y, test_y = train_test_split(
    X, Y, random_state=10, test_size=0.30)

In [6]:
g_model = GaussianNB()
g_model.fit(train_x, train_y)

GaussianNB()

In [7]:
predicted_values = g_model.predict(test_x)

In [8]:

print("\nAccuracy Score\n")
print(metrics.accuracy_score(predicted_values, test_y))


Accuracy Score

0.9580840576438274


In [9]:
print("\nClassification Score\n")
print(metrics.classification_report(predicted_values, test_y))


Classification Score

              precision    recall  f1-score   support

           0       0.99      0.93      0.96     14115
           1       0.93      0.99      0.96     12462

    accuracy                           0.96     26577
   macro avg       0.96      0.96      0.96     26577
weighted avg       0.96      0.96      0.96     26577



In [10]:
# 4.Repeat the model once using only the acceleration values as predictors and then using only the
# gyro values as predictors. Comment on the difference in accuracy between both the models.
# Accelerations as Independent variables

In [11]:
X_A = data.iloc[:, 5:8]
Y_A = data["activity"]


In [12]:
train_x_a, test_x_a, train_y_a, test_y_a = train_test_split(
    X_A, Y_A, random_state=10, test_size=0.30)


In [13]:
g_model.fit(train_x_a, train_y_a)
predicted_values_a = g_model.predict(test_x_a)


In [14]:
print("\nAccuracy Score\n")
print(metrics.accuracy_score(predicted_values_a, test_y_a))



Accuracy Score

0.958648455431388


In [15]:
print("\nClassification Score\n")
print(metrics.classification_report(predicted_values_a, test_y_a))



Classification Score

              precision    recall  f1-score   support

           0       0.99      0.93      0.96     14158
           1       0.92      0.99      0.96     12419

    accuracy                           0.96     26577
   macro avg       0.96      0.96      0.96     26577
weighted avg       0.96      0.96      0.96     26577



In [16]:
# Gyro as Independent variables
X_G = data.iloc[:, 8:]
Y_G = data["activity"]


In [17]:
train_x_g, test_x_g, train_y_g, test_y_g = train_test_split(
    X_G, Y_G, random_state=10, test_size=0.30)


In [18]:
g_model.fit(train_x_g, train_y_g)
predicted_values_g = g_model.predict(test_x_g)


In [19]:
print("\nAccuracy Score\n")
print(metrics.accuracy_score(predicted_values_g, test_y_g))


Accuracy Score

0.6486811905030666


In [20]:
print("\nClassification Score\n")
print(metrics.classification_report(predicted_values_g, test_y_g))


Classification Score

              precision    recall  f1-score   support

           0       0.74      0.62      0.68     15810
           1       0.55      0.69      0.61     10767

    accuracy                           0.65     26577
   macro avg       0.65      0.65      0.65     26577
weighted avg       0.67      0.65      0.65     26577

